#!/bin/sh
#
# Script to build the published winetest.exe on winehq.org.
# This should normally be run from a cron job.
#
# Copyright 2008 Alexandre Julliard
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#

set -e

usage()
{
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  -h, --help     Display this message"
    echo "  -f, --force    Force rebuild even if up-to-date"
    echo ""
}

force=0

while [ $# -gt 0 ]
do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        -f|--force)
            force=1
            shift
            ;;
        *)
            echo "Unknown option $1"
            usage
            exit 1
            ;;
  esac
done

destdir="/home/winehq/opt/winetest/builds"
desturl="http://test.winehq.org/builds"
servicedir="/home/winehq/opt/winetest/winehq-builds/winetest"
toolsdir="/home/winehq/opt/tools"
transldir="/home/winehq/opt/source/transl"

logfile=LOG

# if the log file exists, either a build is in progress or one has failed
if [ -f $logfile -a $force -eq 0 ]
then
    exit 1
fi

umask 022

(
    set -e
    (cd wine && git pull) || exit
    head=$(cd wine && git rev-parse --short=12 HEAD) || exit
    branch=$(cd wine && git symbolic-ref HEAD) || exit
    branch=${branch#refs/heads/}

    if [ -f $destdir/winetest-$head.exe -a -f $destdir/winetest64-$head.exe -a $force -eq 0 ]
    then
        exit 0
    fi

    # first build the native tools

    test -d build64 ||
    (mkdir build64 &&
     cd build64 &&
     ../wine/configure --enable-win64 --with-mingw --without-x --without-freetype) || exit

    (cd build64 && make depend && make __builddeps__) || exit

    # update the translations status

    rm -rf $branch
    mkdir $branch $branch/res
    php $toolsdir/transl/parse_resfiles.php -T ./build64 -w ./$branch 2>>$branch/run.log
    (cd wine && git describe HEAD) >$branch/version
    mv -f $transldir/$branch $transldir/$branch.old
    mv -f $branch $transldir/$branch
    rm -rf $transldir/$branch.old

    echo "translations updated"
    if [ $branch != master ]
    then
        exit 0
    fi

    # then cross-compile the tests

    (cd build64 && make programs/winetest) || exit

    test -d build32 ||
    (mkdir build32 &&
     cd build32 &&
     ../wine/configure --with-mingw --without-x --without-freetype) || exit

    (cd build32 &&
     make depend &&
     make programs/winetest &&
     upx -9 -qq programs/winetest/winetest.exe) || exit

    # install everything

    chmod 644 build32/programs/winetest/winetest.exe build64/programs/winetest/winetest.exe
    mv -f build32/programs/winetest/winetest.exe $destdir/winetest-$head.exe
    mv -f build64/programs/winetest/winetest.exe $destdir/winetest64-$head.exe
    ln -sf winetest-$head.exe $destdir/winetest-latest.exe
    ln -sf winetest64-$head.exe $destdir/winetest64-latest.exe

    rm -f $servicedir/*.cookie $servicedir/*.url
    sha1sum $destdir/winetest-latest.exe | cut -c1-40 > $servicedir/winetest-$head.cookie
    echo "$desturl/winetest-$head.exe" > $servicedir/winetest-$head.url

    echo "winetest-$head.exe built successfully."

) >$logfile 2>&1 && rm -f $logfile

# if the log file is still here, something failed
if [ -f $logfile ]
then
    cat $logfile
    exit 1
fi
